rotations convention: [psi, theta', phi'']

environmental constants:
  g: { value: 9.81, unit: m/s^2 }
  rho: { value: 1025, unit: kg/m^3 }
  nu: { value: 1.18e-6, unit: m^2/s }

environment models:
  - model: no wind
  - model: waves
    discretization:
      ndir: 8
      nfreq: 16
      omega min: { value: 0.1, unit: rad/s }
      omega max: { value: 10, unit: rad/s }
      energy fraction: 0.99
      equal energy bins: false
    spectra:
      - model: airy
        depth: { value: 1000, unit: m }
        seed of the random data generator: 2
        stretching:
          delta: 1
          h: { unit: m, value: 0 }
        directional spreading:
          type: cos2s
          s: 2
          waves propagating to: { value: 0, unit: deg }
        spectral density:
          type: jonswap
          Hs: { value: 1.5, unit: m }
          Tp: { value: 3, unit: s }
          gamma: 1.2
  - model: ekman current
    #seabed depth: 123
    seabed file: seabed/seabed.png
    latitude: { value: 43, unit: deg }
    top layer thickness: { value: 5, unit: m}
    bottom layer thickness: { value: 8, unit: m}
    current velocity: { value: 0.1, unit: m/s }
    current orientation: { value: 0, unit: deg }
    U10: { value: 1, unit: m/s }
    wind orientation: { value: 0, unit: rad }

# Fixed frame: NED
bodies: # All bodies have NED as parent frame
  - name: dtmb
    mesh: dtmb_hull/meshes/dtmb.stl

    position of body frame relative to mesh:
      frame: mesh
      x: { value: 70.27, unit: m }
      y: { value: 0, unit: m }
      z: { value: -7.55, unit: m }
      phi: { value: 0, unit: rad }
      theta: { value: 0, unit: rad }
      psi: { value: 0, unit: rad }

    initial position of body frame relative to NED:
      frame: NED
      x: { value: 0, unit: m }
      y: { value: 0, unit: m }
      z: { value: 0, unit: m }
      phi: { value: 0, unit: deg }
      theta: { value: 0, unit: deg }
      psi: { value: 0, unit: deg }

    initial velocity of body frame relative to NED:
      frame: body
      u: { value: 0, unit: m/s }
      v: { value: 0, unit: m/s }
      w: { value: 0, unit: m/s }
      p: { value: 0, unit: rad/s }
      q: { value: 0, unit: rad/s }
      r: { value: 0, unit: rad/s }

    dynamics:
      hydrodynamic forces calculation point in body frame:
        x: { value: 0, unit: m }
        y: { value: 0, unit: m }
        z: { value: 3.45, unit: m }

      centre of inertia:
        frame: dtmb
        x: { value: 0, unit: m }
        y: { value: 0, unit: m }
        z: { value: 0, unit: m }

      ? rigid body inertia matrix at the center of buoyancy projected in the body frame
      : frame: body
        row 1: [8.569e6, 0, 0, 0, 0, 0]
        row 2: [0, 8.569e6, 0, 0, 0, 0]
        row 3: [0, 0, 8.569e6, 0, 0, 0]
        row 4: [0, 0, 0, 4.271e8, 0, 0]
        row 5: [0, 0, 0, 0, 1.080e10, 0]
        row 6: [0, 0, 0, 0, 0, 1.080e10]

      # added mass matrix at the center of gravity and projected in the body frame:
      #     from raodb: issue_196_test.raodb.ini
      added mass matrix at the center of buoyancy projected in the body frame:
        frame: body
        row 1:
          [8.979E+04, 0.000E+00, -1.981E+05, 0.000E+00, -1.962E+07, 0.000E+00]
        row 2:
          [0.000E+00, 2.172E+06, 0.000E+00, 1.135E+06, 0.000E+00, 2.523E+07]
        row 3:
          [-1.981E+05, 0.000E+00, 9.680E+06, 0.000E+00, 6.716E+07, 0.000E+00]
        row 4:
          [0.000E+00, 1.135E+06, 0.000E+00, 3.865E+07, 0.000E+00, -2.228E+08]
        row 5:
          [-1.962E+07, 0.000E+00, 6.716E+07, 0.000E+00, 9.117E+09, 0.000E+00]
        row 6:
          [0.000E+00, 2.523E+07, 0.000E+00, -2.228E+08, 0.000E+00, 3.338E+09]

    external forces:
      - model: gravity

      - model: non-linear hydrostatic (fast)

#      - model: non-linear Froude-Krylov

      - model: linear damping
        damping matrix at the center of gravity projected in the body frame:
          frame: dtmb
          row 1: [1.0e5, 0, 0, 0, 0, 0] #added 1.0e5 for stability
          row 2: [0, 1.0e5, 0, 0, 0, 0] #added 1.0e5 for stability
          row 3: [0, 0, 8.86e6, 0, 0, 0]
          row 4: [0, 0, 0, 3.18e7, 0, 0]
          row 5: [0, 0, 0, 0, 1.01e10, 0]
          row 6: [0, 0, 0, 0, 0, 1.0e5] #added 1.0e5 for stability

      - model: quadratic damping
        damping matrix at the center of gravity projected in the body frame:
          frame: dtmb
          row 1: [0, 0, 0, 0, 0, 0]
          row 2: [0, 0, 0, 0, 0, 0]
          row 3: [0, 0, 0, 0, 0, 0]
          row 4: [0, 0, 0, 1.16e8, 0, 0]
          row 5: [0, 0, 0, 0, 0, 0]
          row 6: [0, 0, 0, 0, 0, 0]